name: Render Web Service keep-alive backup

on:
  schedule:
    - cron: '*/11 * * * *'
jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X GET "${API_URL%/}/hello/github-actions-backup-1"