name: Call API Every 5 Minutes

on:
  schedule:
    - cron: '*/7 * * * *' # Run every 5 minutes

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X GET $API_URL
